name: "Analyze PR Size"
description: "Summarize PR size (files, additions/deletions) and post an idempotent PR comment"
inputs:
  github_token:
    required: true
  max_files:
    required: false
    default: "500"
  add_label:
    description: "Add a size label (size:XS … size:XL) to the PR"
    required: false
    default: "false"
  step_summary:
    description: "Write the size summary to the GitHub Actions Step Summary"
    required: false
    default: "false"
  ignore_patterns:
    description: "Comma-separated glob patterns for generated/lock files to exclude from size calculation"
    required: false
    default: "dist/**,*.min.js,*.min.css,package-lock.json,yarn.lock,pnpm-lock.yaml,*.generated.*"

  xs_lines:
    required: false
    default: "50"
  s_lines:
    required: false
    default: "200"
  m_lines:
    required: false
    default: "500"
  l_lines:
    required: false
    default: "1000"

  xs_files:
    required: false
    default: "2"
  s_files:
    required: false
    default: "5"
  m_files:
    required: false
    default: "15"
  l_files:
    required: false
    default: "30"

outputs:
  size:
    description: "Computed size bucket (XS, S, M, L, XL)"
  total_lines:
    description: "Total lines changed (additions + deletions)"
  file_count:
    description: "Number of files changed"
  pr_age_hours:
    description: "PR age in hours since creation"
runs:
  using: "node20"
  main: "dist/index.js"